"""
dg_comparison.py  —  Model Comparison & Final Selection
========================================================
Compares conventional and unconventional predictions for DTC / DTS sonic logs
stored in st.session_state.df.

Sections
--------
  A. Target & Ground-Truth Selection
  B. Discover Available Prediction Columns
  C. Model Multi-Select
  D. Metrics Table  (RMSE | MAE | R²)  — sorted by RMSE
  E. Bar Chart Comparison  (RMSE and R²)
  F. Depth-Track Line Plot  (optional)
  G. Best-Model Banner
  H. Final Model Selection → stores <target>_final in session_state
  I. Uncertainty Quantification  (multi-model ensemble)

Public entry point
------------------
    from dg_comparison import render
    render(df)
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from dg_utils import (
    COLORS,
    find_col,
    numeric_cols,
    section_header,
    plotly_depth_track,
    plotly_scatter,
    plotly_residual_hist,
)


# ═══════════════════════════════════════════════════════════════════════════ #
# CONSTANTS
# ═══════════════════════════════════════════════════════════════════════════ #

# Unconventional prediction suffix (generated by dg_unconventional.py)
_UNC_SUFFIX = "_pred"

# Ground-truth column candidates per target
_GT_CANDIDATES: dict[str, list[str]] = {
    "DTC": ["DTC", "DTCO", "DT", "AC", "SONIC"],
    "DTS": ["DTS", "DTSM", "DT4S", "SS"],
}


# ═══════════════════════════════════════════════════════════════════════════ #
# CORE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════ #

def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float | None]:
    """
    Compute RMSE, MAE, and R² safely, ignoring NaNs.

    Parameters
    ----------
    y_true : ground-truth array (may contain NaN)
    y_pred : predicted array   (may contain NaN)

    Returns
    -------
    dict with keys 'RMSE', 'MAE', 'R²'  — float or None if insufficient data
    """
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    valid = ~(np.isnan(y_true) | np.isnan(y_pred))
    n_valid = int(valid.sum())

    if n_valid < 2:
        return {"RMSE": None, "MAE": None, "R²": None}

    yt = y_true[valid]
    yp = y_pred[valid]

    residuals = yt - yp
    rmse = float(np.sqrt(np.mean(residuals ** 2)))
    mae  = float(np.mean(np.abs(residuals)))

    ss_res = float(np.sum(residuals ** 2))
    ss_tot = float(np.sum((yt - np.mean(yt)) ** 2))
    r2     = (1.0 - ss_res / ss_tot) if ss_tot > 0 else None

    return {"RMSE": rmse, "MAE": mae, "R²": r2}


def get_available_models(df: pd.DataFrame, target_col: str) -> dict[str, str]:
    """
    Dynamically detect all prediction columns relevant to `target_col`.

    Strategy
    --------
    1. ML/DL per-model columns: pattern  '<target>_<model_key>_pred'
       e.g.  DTC_xgboost_pred, DTC_cnn_bilstm_pred
    2. Legacy ML/DL column: exact pattern '<target>_pred'  (backward compat)
    3. Conventional: columns starting with velocity-domain tag
       ('Vp' for DTC, 'Vs' for DTS) that contain 'pred'
    4. Fallback: any column containing the target name and 'pred'

    Returns
    -------
    dict { display_label → df_column_name }
    """
    _ML_KEYS = [
        "random_forest", "xgboost", "cnn_bilstm",
    ]
    _ML_LABELS = {
        "random_forest": "Random Forest",
        "xgboost":       "XGBoost",
        "cnn_bilstm":    "CNN-BiLSTM",
    }

    models: dict[str, str] = {}
    seen_cols: set[str] = set()

    # 1. Per-model ML/DL columns ──────────────────────────────────────────────
    for key in _ML_KEYS:
        col = f"{target_col}_{key}_pred"
        if col in df.columns and col not in seen_cols:
            label = _ML_LABELS.get(key, key)
            models[f"[ML/DL] {label}"] = col
            seen_cols.add(col)

    # 2. Legacy single ML/DL column ───────────────────────────────────────────
    legacy_col = f"{target_col}{_UNC_SUFFIX}"
    if legacy_col in df.columns and legacy_col not in seen_cols:
        models[f"[ML/DL] {legacy_col}"] = legacy_col
        seen_cols.add(legacy_col)

    # 3. Conventional — velocity-domain prefix ────────────────────────────────
    vel_tag = "Vp" if target_col == "DTC" else "Vs"
    for col in df.columns:
        if col in seen_cols:
            continue
        if col.startswith(vel_tag) and "pred" in col.lower():
            models[f"[Conv] {col}"] = col
            seen_cols.add(col)

    # 4. Fallback — any col containing target name + pred ─────────────────────
    tgt_lower = target_col.lower()
    for col in df.columns:
        if col in seen_cols:
            continue
        cl = col.lower()
        if tgt_lower in cl and "pred" in cl:
            models[f"[Conv] {col}"] = col
            seen_cols.add(col)

    return models


def _depth_col(df: pd.DataFrame) -> str | None:
    """Return best-guess depth column name, or None."""
    return find_col(df, ["DEPTH", "MD", "DEPT", "TVD", "DEPTH_MD"])


# ═══════════════════════════════════════════════════════════════════════════ #
# PLOT HELPERS
# ═══════════════════════════════════════════════════════════════════════════ #

def plot_comparison(
    metrics_df: pd.DataFrame,
    metric: str,
    target_col: str,
) -> None:
    """
    Horizontal bar chart for a single metric.
    Green = best, red = worst, blue = middle.
    """
    sub = metrics_df.dropna(subset=[metric]).copy()
    if sub.empty:
        st.info(f"No valid {metric} values to plot.")
        return

    ascending = metric in ("RMSE", "MAE")   # lower is better
    sub = sub.sort_values(metric, ascending=ascending).reset_index(drop=True)

    n = len(sub)
    bar_colors = []
    for i in range(n):
        if i == 0:
            bar_colors.append(COLORS[2])   # green = best
        elif i == n - 1:
            bar_colors.append(COLORS[1])   # red = worst
        else:
            bar_colors.append(COLORS[0])   # blue = middle

    fig = go.Figure(
        go.Bar(
            x=sub[metric],
            y=sub["Model"],
            orientation="h",
            marker_color=bar_colors,
            text=sub[metric].apply(lambda v: f"{v:.4f}"),
            textposition="outside",
        )
    )
    direction = "lower = better" if ascending else "higher = better"
    fig.update_layout(
        title=f"{metric} by model ({direction})",
        height=max(280, 50 * n + 80),
        xaxis_title=metric,
        yaxis_title="",
        yaxis=dict(autorange="reversed"),
        margin=dict(l=20, r=70, t=50, b=40),
    )
    st.plotly_chart(
        fig,
        use_container_width=True,
        key=f"dg_cmp_bar_{target_col}_{metric}",
    )


def _plot_depth_overlay(
    df: pd.DataFrame,
    true_col: str | None,
    model_rows: list[dict],
    target_col: str,
) -> None:
    """Depth-track overlay for all selected models + ground truth."""
    curves, clabels, colors = [], [], []

    if true_col and true_col in df.columns:
        curves.append(true_col)
        clabels.append("Ground Truth")
        colors.append("#212121")

    for i, row in enumerate(model_rows):
        col = row["Column"]
        if col in df.columns:
            curves.append(col)
            clabels.append(row["Model"])
            colors.append(COLORS[i % len(COLORS)])

    if not curves:
        st.info("No data available for depth-track plot.")
        return

    fig = plotly_depth_track(
        df, curves, clabels, colors,
        f"{target_col} — Predictions vs Depth",
        target_col,
    )
    st.plotly_chart(fig, use_container_width=True, key=f"dg_cmp_depth_{target_col}")


# ═══════════════════════════════════════════════════════════════════════════ #
# UNCERTAINTY QUANTIFICATION
# ═══════════════════════════════════════════════════════════════════════════ #

def compute_uncertainty(predictions_array: np.ndarray) -> dict[str, np.ndarray]:
    """
    Compute mean, std, and 95% confidence intervals from multi-model predictions.

    Parameters
    ----------
    predictions_array : np.ndarray, shape (n_models, n_samples)
        Each row is one model's prediction vector.

    Returns
    -------
    dict with keys:
        'mean'  – per-sample mean across models
        'std'   – per-sample standard deviation across models
        'lower' – lower bound of 95% CI  (mean - 1.96 * std)
        'upper' – upper bound of 95% CI  (mean + 1.96 * std)
        'ci_width' – width of the 95% CI (upper - lower)
    """
    # Use nanmean / nanstd so models with partial NaNs don't poison everything
    mean  = np.nanmean(predictions_array, axis=0)
    std   = np.nanstd(predictions_array,  axis=0)
    lower = mean - 1.96 * std
    upper = mean + 1.96 * std
    return {
        "mean":     mean,
        "std":      std,
        "lower":    lower,
        "upper":    upper,
        "ci_width": upper - lower,
    }


def compute_residual_uncertainty(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    window: int = 50,
) -> np.ndarray:
    """
    Estimate depth-varying uncertainty from rolling residual standard deviation.

    Parameters
    ----------
    y_true  : ground-truth array  (may contain NaN)
    y_pred  : predicted array     (may contain NaN)
    window  : rolling window size (number of depth samples)

    Returns
    -------
    np.ndarray of the same length as y_true — rolling std of residuals.
    NaN where residuals are not computable.
    """
    residual = np.asarray(y_true, dtype=float) - np.asarray(y_pred, dtype=float)
    s = pd.Series(residual)
    rolling_std = s.rolling(window=window, center=True, min_periods=5).std()
    return rolling_std.values


def _plot_uncertainty_depth(
    df: pd.DataFrame,
    unc_dict: dict[str, np.ndarray],
    true_col: str | None,
    target_col: str,
) -> go.Figure:
    """
    Depth track with shaded 95% confidence interval and ensemble mean.
    """
    depth_col = _depth_col(df)
    depth = df[depth_col].values if depth_col else np.arange(len(df))

    mean  = unc_dict["mean"]
    lower = unc_dict["lower"]
    upper = unc_dict["upper"]

    fig = go.Figure()

    # 95% CI shaded band
    fig.add_trace(go.Scatter(
        x=np.concatenate([upper, lower[::-1]]),
        y=np.concatenate([depth, depth[::-1]]),
        fill="toself",
        fillcolor="rgba(25,118,210,0.18)",
        line=dict(color="rgba(0,0,0,0)"),
        name="95% CI",
        hoverinfo="skip",
    ))

    # Ensemble mean
    fig.add_trace(go.Scatter(
        x=mean, y=depth, mode="lines",
        line=dict(color="#1976D2", width=2),
        name="Ensemble Mean",
    ))

    # Ground truth if available
    if true_col and true_col in df.columns:
        fig.add_trace(go.Scatter(
            x=df[true_col].values, y=depth, mode="lines",
            line=dict(color="#E53935", dash="dot", width=1.5),
            name="Ground Truth",
        ))

    fig.update_yaxes(autorange="reversed", title="Depth")
    fig.update_xaxes(title=f"{target_col} (µs/ft)")
    fig.update_layout(
        title=f"{target_col} — Ensemble Mean ± 95% Confidence Interval",
        height=520,
        hovermode="y unified",
        margin=dict(l=60, r=20, t=55, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    return fig


def _plot_uncertainty_std_depth(
    df: pd.DataFrame,
    std_array: np.ndarray,
    target_col: str,
) -> go.Figure:
    """
    Depth track coloured by uncertainty magnitude (std per depth sample).
    """
    depth_col = _depth_col(df)
    depth = df[depth_col].values if depth_col else np.arange(len(df))

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=std_array, y=depth, mode="lines",
        line=dict(color="#F57F17", width=1.8),
        fill="tozerox",
        fillcolor="rgba(245,127,23,0.15)",
        name="Model Std Dev",
    ))
    fig.update_yaxes(autorange="reversed", title="Depth")
    fig.update_xaxes(title=f"Std Dev of {target_col} Predictions")
    fig.update_layout(
        title=f"{target_col} — Per-Depth Prediction Uncertainty (Std Dev)",
        height=520,
        hovermode="y unified",
        margin=dict(l=60, r=20, t=55, b=40),
    )
    return fig


def _plot_uncertainty_crossplot(
    y_true: np.ndarray,
    y_mean: np.ndarray,
    y_std: np.ndarray,
    target_col: str,
) -> go.Figure:
    """
    Actual vs Ensemble-Mean scatter, coloured by prediction uncertainty (std).
    """
    valid = ~(np.isnan(y_true) | np.isnan(y_mean) | np.isnan(y_std))
    yt = y_true[valid]
    yp = y_mean[valid]
    ys = y_std[valid]

    if len(yt) < 2:
        fig = go.Figure()
        fig.update_layout(title="Not enough valid data for crossplot")
        return fig

    mn = min(yt.min(), yp.min())
    mx = max(yt.max(), yp.max())

    fig = go.Figure()
    # 1:1 line
    fig.add_trace(go.Scatter(
        x=[mn, mx], y=[mn, mx], mode="lines",
        line=dict(color="gray", dash="dash", width=1),
        name="1:1", showlegend=True,
    ))
    # Scatter coloured by uncertainty
    fig.add_trace(go.Scatter(
        x=yt, y=yp, mode="markers",
        marker=dict(
            color=ys,
            colorscale="YlOrRd",
            size=5,
            opacity=0.75,
            colorbar=dict(title="Std Dev", thickness=14),
            showscale=True,
        ),
        name="Samples",
        hovertemplate=(
            f"Actual: %{{x:.2f}}<br>Predicted: %{{y:.2f}}<br>Std: %{{marker.color:.2f}}<extra></extra>"
        ),
    ))
    fig.update_layout(
        title=f"{target_col} — Actual vs Ensemble Mean (colour = uncertainty)",
        xaxis_title=f"Actual {target_col}",
        yaxis_title=f"Ensemble Mean {target_col}",
        height=450,
        margin=dict(l=60, r=20, t=55, b=40),
    )
    return fig


def _plot_uncertainty_histogram(
    std_array: np.ndarray,
    target_col: str,
) -> go.Figure:
    """
    Distribution of per-depth uncertainty (std) values.
    """
    valid = std_array[~np.isnan(std_array)]
    fig = go.Figure()
    fig.add_trace(go.Histogram(
        x=valid,
        nbinsx=40,
        marker_color="#1976D2",
        opacity=0.8,
        name="Std Dev",
    ))
    # Annotate median and p90
    if len(valid) > 0:
        med = float(np.median(valid))
        p90 = float(np.percentile(valid, 90))
        fig.add_vline(x=med, line_dash="dash", line_color="#E53935",
                      annotation_text=f"Median: {med:.3f}",
                      annotation_position="top right")
        fig.add_vline(x=p90, line_dash="dot",  line_color="#F57F17",
                      annotation_text=f"P90: {p90:.3f}",
                      annotation_position="top left")
    fig.update_layout(
        title=f"{target_col} — Distribution of Prediction Uncertainty (Std Dev)",
        xaxis_title=f"Std Dev of {target_col} Predictions",
        yaxis_title="Count",
        height=380,
        margin=dict(l=60, r=20, t=55, b=40),
    )
    return fig


def _render_uncertainty_section(
    df: pd.DataFrame,
    model_rows: list[dict],
    target_col: str,
    true_col: str | None,
    section_label: str = "H",
) -> None:
    """
    Full Streamlit UI block for uncertainty quantification.
    Renders only when the parent checkbox is enabled.
    """
    st.markdown(f"### {section_label} · Uncertainty Quantification")
    st.markdown(
        """
        **Multi-model ensemble uncertainty** uses the spread across all selected models
        as a proxy for prediction uncertainty.  
        - **Std Dev** captures *epistemic* uncertainty (model disagreement).  
        - **95% CI** = Mean ± 1.96 × Std Dev.  
        - High-uncertainty zones may indicate poor data quality, complex lithology, or model instability.
        """
    )

    # Gather prediction arrays for all valid model columns
    pred_cols = [r["Column"] for r in model_rows if r["Column"] in df.columns]
    n_models  = len(pred_cols)

    if n_models < 2:
        st.warning(
            "⚠️ Uncertainty analysis requires **at least 2 models**.  "
            "Select more models in Section B."
        )
        return

    # Build (n_models, n_samples) array
    pred_matrix = np.vstack([df[c].values.astype(float) for c in pred_cols])
    unc = compute_uncertainty(pred_matrix)

    # ── Summary metrics ──────────────────────────────────────────────────────
    st.markdown("#### Summary Metrics")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Models",           f"{n_models}")
    m2.metric("Mean Std Dev",     f"{float(np.nanmean(unc['std'])):.4f}")
    m3.metric("Mean CI Width",    f"{float(np.nanmean(unc['ci_width'])):.4f}")
    m4.metric("Max Std Dev",      f"{float(np.nanmax(unc['std'])):.4f}")

    # ── Per-model average uncertainty ────────────────────────────────────────
    st.markdown("#### Per-Model Average Uncertainty Contribution")
    per_model_data = []
    for col, row in zip(pred_cols, model_rows):
        vals = df[col].values.astype(float)
        abs_dev = np.abs(vals - unc["mean"])
        per_model_data.append({
            "Model":           row["Model"],
            "Avg |Deviation|": float(np.nanmean(abs_dev)),
            "Max |Deviation|": float(np.nanmax(abs_dev)),
        })
    per_model_df = pd.DataFrame(per_model_data).sort_values(
        "Avg |Deviation|", ascending=False
    ).reset_index(drop=True)
    st.dataframe(
        per_model_df.style.format({
            "Avg |Deviation|": "{:.5f}",
            "Max |Deviation|": "{:.5f}",
        }),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    # ── Toggle: confidence interval depth plot ───────────────────────────────
    show_ci = st.checkbox(
        "Show 95% Confidence Interval (depth track)",
        value=True,
        key=f"dg_unc_ci_toggle_{target_col}",
    )
    if show_ci:
        st.plotly_chart(
            _plot_uncertainty_depth(df, unc, true_col, target_col),
            use_container_width=True,
            key=f"dg_unc_depth_{target_col}",
        )

    # ── Toggle: uncertainty magnitude depth plot ─────────────────────────────
    show_std = st.checkbox(
        "Show per-depth Std Dev (uncertainty magnitude)",
        value=True,
        key=f"dg_unc_std_toggle_{target_col}",
    )
    if show_std:
        st.plotly_chart(
            _plot_uncertainty_std_depth(df, unc["std"], target_col),
            use_container_width=True,
            key=f"dg_unc_std_{target_col}",
        )

    # ── Crossplot coloured by uncertainty (needs ground truth) ───────────────
    if true_col and true_col in df.columns:
        show_cross = st.checkbox(
            "Show Actual vs Predicted crossplot (coloured by uncertainty)",
            value=True,
            key=f"dg_unc_cross_toggle_{target_col}",
        )
        if show_cross:
            y_true = df[true_col].values.astype(float)
            st.plotly_chart(
                _plot_uncertainty_crossplot(y_true, unc["mean"], unc["std"], target_col),
                use_container_width=True,
                key=f"dg_unc_cross_{target_col}",
            )
    else:
        st.caption("ℹ️ Crossplot requires a ground-truth column (Section A).")

    # ── Uncertainty histogram ────────────────────────────────────────────────
    show_hist = st.checkbox(
        "Show uncertainty distribution histogram",
        value=True,
        key=f"dg_unc_hist_toggle_{target_col}",
    )
    if show_hist:
        st.plotly_chart(
            _plot_uncertainty_histogram(unc["std"], target_col),
            use_container_width=True,
            key=f"dg_unc_hist_{target_col}",
        )

    # ── Residual-based uncertainty (optional, needs GT) ──────────────────────
    if true_col and true_col in df.columns:
        st.divider()
        with st.expander("🔬 Residual-Based Uncertainty (optional, single best model)", expanded=False):
            st.markdown(
                "Rolling standard deviation of residuals from the best-performing model.  \n"
                "High values highlight depth intervals where even the best model struggles."
            )
            best_row = model_rows[0]  # already sorted by RMSE
            y_true = df[true_col].values.astype(float)
            y_pred = df[best_row["Column"]].values.astype(float)
            window = st.slider(
                "Rolling window (depth samples)",
                min_value=10, max_value=200, value=50, step=10,
                key=f"dg_unc_window_{target_col}",
            )
            resid_std = compute_residual_uncertainty(y_true, y_pred, window=window)
            depth_col = _depth_col(df)
            depth_vals = df[depth_col].values if depth_col else np.arange(len(df))

            fig_res = go.Figure()
            fig_res.add_trace(go.Scatter(
                x=resid_std, y=depth_vals, mode="lines",
                line=dict(color="#2E7D32", width=1.8),
                fill="tozerox",
                fillcolor="rgba(46,125,50,0.15)",
                name="Residual Std",
            ))
            fig_res.update_yaxes(autorange="reversed", title="Depth")
            fig_res.update_xaxes(title=f"Residual Std of {target_col}")
            fig_res.update_layout(
                title=f"{target_col} — Residual-Based Uncertainty (Best Model: {best_row['Model']})",
                height=480, hovermode="y unified",
                margin=dict(l=60, r=20, t=55, b=40),
            )
            st.plotly_chart(fig_res, use_container_width=True,
                            key=f"dg_unc_resid_{target_col}")

    # ── Save ensemble mean to session ────────────────────────────────────────
    st.divider()
    st.markdown("#### 💾 Save Ensemble Mean as Output Column")
    ens_col = f"{target_col}_ensemble_mean"
    if st.button(
        f"Save ensemble mean → `{ens_col}`",
        key=f"dg_unc_save_{target_col}",
    ):
        st.session_state.df[ens_col] = unc["mean"]
        st.session_state.df[f"{target_col}_ensemble_std"]   = unc["std"]
        st.session_state.df[f"{target_col}_ensemble_lower"] = unc["lower"]
        st.session_state.df[f"{target_col}_ensemble_upper"] = unc["upper"]
        n_saved = int(pd.Series(unc["mean"]).notna().sum())
        st.success(
            f"✅ Saved `{ens_col}` and associated uncertainty columns "
            f"({n_saved:,} values). Columns added:\n"
            f"- `{target_col}_ensemble_mean`\n"
            f"- `{target_col}_ensemble_std`\n"
            f"- `{target_col}_ensemble_lower`\n"
            f"- `{target_col}_ensemble_upper`"
        )


# ═══════════════════════════════════════════════════════════════════════════ #
# PUBLIC ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════ #

def render(df: pd.DataFrame) -> None:  # noqa: C901  (complexity OK for UI module)
    section_header(
        "📊",
        "Model Comparison & Final Selection",
        "Compare conventional and ML/DL predictions for DTC / DTS sonic logs",
    )

    # Guard ───────────────────────────────────────────────────────────────────
    if "df" not in st.session_state or st.session_state.df is None:
        st.warning("No dataset loaded. Upload data first.")
        return

    df = st.session_state.df   # always reflect live session

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION A — Target & Ground-Truth
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### A · Select Target & Ground Truth")

    col_a1, col_a2 = st.columns(2)

    target_display = col_a1.selectbox(
        "Select Sonic Target for Comparison",
        options=["DTC (P-wave Sonic)", "DTS (S-wave Sonic)"],
        key="dg_cmp_target",
        help="DTC = compressional slowness. DTS = shear slowness.",
    )
    target_col = "DTC" if "DTC" in target_display else "DTS"

    num  = numeric_cols(df)
    opts = ["None"] + num
    auto_gt = find_col(df, _GT_CANDIDATES.get(target_col, [target_col]))
    gt_idx  = opts.index(auto_gt) if (auto_gt and auto_gt in opts) else 0

    true_col_sel = col_a2.selectbox(
        f"Ground-Truth Column for {target_col}",
        options=opts,
        index=gt_idx,
        key="dg_cmp_gt_col",
        help="Optional — required to compute RMSE / MAE / R².",
    )
    true_col: str | None = None if true_col_sel == "None" else true_col_sel

    if true_col is None:
        st.info(
            "ℹ️ No ground-truth column selected — metrics cannot be computed. "
            "Visual comparisons and final model selection are still available."
        )

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION B — Detect Available Prediction Columns
    # ═══════════════════════════════════════════════════════════════════════ #
    available_models: dict[str, str] = get_available_models(df, target_col)

    if not available_models:
        st.warning(
            f"No prediction columns found for **{target_col}**.\n\n"
            "Run the **Conventional** or **Unconventional** workflows first, "
            "then return here."
        )
        return

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION C — Model Multi-Select
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### B · Select Models to Compare")

    all_labels = list(available_models.keys())

    selected_labels: list[str] = st.multiselect(
        "Select Models to Compare",
        options=all_labels,
        default=all_labels,
        key="dg_cmp_model_select",
        help="All detected prediction columns are listed. Deselect any you wish to exclude.",
    )

    if not selected_labels:
        st.info("Select at least one model to continue.")
        return

    # Build unified row records
    model_rows: list[dict] = []
    for lbl in selected_labels:
        col = available_models[lbl]
        if col not in df.columns:
            st.caption(f"⚠️ Column `{col}` missing from dataset — skipped.")
            continue

        if true_col and true_col in df.columns:
            m = compute_metrics(
                df[true_col].values.astype(float),
                df[col].values.astype(float),
            )
        else:
            m = {"RMSE": None, "MAE": None, "R²": None}

        model_rows.append({
            "Model":  lbl.split("] ", 1)[-1],   # short name without tag
            "Column": col,
            "Type":   "ML/DL" if lbl.startswith("[ML") else "Conventional",
            "RMSE":   m["RMSE"],
            "MAE":    m["MAE"],
            "R²":     m["R²"],
        })

    if not model_rows:
        st.warning("No valid prediction data found for the selected models.")
        return

    metrics_df = pd.DataFrame(model_rows)
    has_metrics = metrics_df["RMSE"].notna().any()

    # Sort by RMSE ascending when metrics are available
    if has_metrics:
        metrics_df = metrics_df.sort_values("RMSE", ascending=True).reset_index(drop=True)
        model_rows = metrics_df.to_dict("records")

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION D — Metrics Table
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### C · Performance Metrics")

    display_df = metrics_df[["Model", "Type", "RMSE", "MAE", "R²"]].copy()
    fmt = {c: "{:.5f}" for c in ["RMSE", "MAE", "R²"] if c in display_df.columns}

    st.dataframe(
        display_df.style.format(fmt, na_rep="—"),
        use_container_width=True,
        hide_index=True,
    )

    if not has_metrics:
        st.caption(
            "Assign a ground-truth column (Section A) to compute RMSE / MAE / R²."
        )

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION E — Bar Charts
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### D · Metric Comparison Charts")

    if has_metrics:
        tab_rmse, tab_mae, tab_r2 = st.tabs(["RMSE ↓", "MAE ↓", "R² ↑"])
        with tab_rmse:
            plot_comparison(metrics_df, "RMSE", target_col)
        with tab_mae:
            plot_comparison(metrics_df, "MAE",  target_col)
        with tab_r2:
            plot_comparison(metrics_df, "R²",   target_col)
    else:
        st.info("Metric charts require a ground-truth column.")

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION F — Depth-Track Visualisation
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### E · Depth-Track Visualisation")

    show_depth = st.checkbox(
        "Show depth-track overlay",
        value=True,
        key="dg_cmp_depth_toggle",
    )

    if show_depth:
        _plot_depth_overlay(df, true_col, model_rows, target_col)

        # Focused scatter + residual
        if true_col and true_col in df.columns:
            st.markdown("**Scatter & residual — focused on one model:**")
            focus_short = st.selectbox(
                "Model for detail view",
                options=[r["Model"] for r in model_rows],
                key="dg_cmp_focus_model",
            )
            focus_row = next((r for r in model_rows if r["Model"] == focus_short), None)

            if focus_row and focus_row["Column"] in df.columns:
                yt = df[true_col].values.astype(float)
                yp = df[focus_row["Column"]].values.astype(float)

                sc1, sc2 = st.columns(2)
                with sc1:
                    st.plotly_chart(
                        plotly_scatter(yt, yp, target_col, focus_short),
                        use_container_width=True,
                        key=f"dg_cmp_scatter_{target_col}",
                    )
                with sc2:
                    st.plotly_chart(
                        plotly_residual_hist(yt, yp, target_col),
                        use_container_width=True,
                        key=f"dg_cmp_resid_{target_col}",
                    )

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION G — Best Model Banner
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### F · Best Model")

    if has_metrics:
        best = metrics_df.iloc[0]    # sorted by RMSE ascending
        best_name = best["Model"]
        bg1, bg2, bg3 = st.columns(3)
        bg1.success(f"🏆 **Best Model:** {best_name}")
        if best["RMSE"] is not None:
            bg2.metric("Best RMSE", f"{best['RMSE']:.4f}")
        if best["R²"] is not None:
            bg3.metric("Best R²", f"{best['R²']:.4f}")
    else:
        best_name = None
        st.info(
            "Automatic best-model ranking requires a ground-truth column. "
            "You can still manually select the final model below."
        )

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION H — Final Model Selection & Save
    # ═══════════════════════════════════════════════════════════════════════ #
    st.markdown("### G · Final Model Selection")

    final_out_col = f"{target_col}_final"
    st.caption(
        f"The selected model's predictions will be saved as **`{final_out_col}`** "
        "in your dataset and can be used downstream."
    )

    short_names = [r["Model"] for r in model_rows]
    default_idx = 0
    if best_name and best_name in short_names:
        default_idx = short_names.index(best_name)

    final_label = st.selectbox(
        "Select Model to Use as Final Output",
        options=short_names,
        index=default_idx,
        key="dg_cmp_final_select",
        help="Pre-selected to the best-performing model (lowest RMSE) when metrics are available.",
    )

    final_row = next((r for r in model_rows if r["Model"] == final_label), None)
    if final_row is None:
        st.error("Could not resolve the selected model.")
        return

    final_src = final_row["Column"]
    col_h1, col_h2 = st.columns([3, 1])
    col_h1.markdown(f"**Source:** `{final_src}` → **Output:** `{final_out_col}`")

    if col_h2.button("💾 Save as Final Output", type="primary", key="dg_cmp_save_btn"):
        if final_src not in df.columns:
            st.error(f"Source column `{final_src}` not found in dataset.")
        else:
            st.session_state.df[final_out_col] = st.session_state.df[final_src].copy()
            n_saved = int(st.session_state.df[final_out_col].notna().sum())
            st.success(
                f"✅ **{final_label}** saved to `{final_out_col}` — "
                f"{n_saved:,} values written."
            )
            vals = st.session_state.df[final_out_col].dropna()
            if len(vals):
                s1, s2, s3, s4 = st.columns(4)
                s1.metric("Count",  f"{len(vals):,}")
                s2.metric("Mean",   f"{vals.mean():.3f}")
                s3.metric("Min",    f"{vals.min():.3f}")
                s4.metric("Max",    f"{vals.max():.3f}")

    # Status if final column already exists
    if final_out_col in st.session_state.df.columns:
        n_exist = int(st.session_state.df[final_out_col].notna().sum())
        st.caption(
            f"ℹ️ `{final_out_col}` already exists with {n_exist:,} non-null values. "
            "Saving will overwrite it."
        )

    st.divider()

    # ═══════════════════════════════════════════════════════════════════════ #
    # SECTION I — Uncertainty Quantification
    # ═══════════════════════════════════════════════════════════════════════ #

    enable_unc = st.checkbox(
        "🔍 Enable Uncertainty Analysis",
        value=False,
        key=f"dg_cmp_unc_enable_{target_col}",
        help=(
            "Quantify prediction uncertainty using multi-model ensemble spread. "
            "Requires ≥2 models selected above."
        ),
    )

    if enable_unc:
        _render_uncertainty_section(
            df=st.session_state.df,
            model_rows=model_rows,
            target_col=target_col,
            true_col=true_col,
            section_label="I",
        )
    else:
        st.info(
            "☝️ Enable **Uncertainty Analysis** above to quantify and visualise "
            "prediction confidence intervals and model disagreement."
        )


